
##### Epi parameters: means 
# case type distribution
q_A: 0.36
q_Im: 0.5843

# transmissibility
beta_pre: 1.25

# latency
delta: 0.25   # 1/4

## FOI
# FOI from Asymptomatic
gamma_A: 0.1428571   # 1/7
k_A: 0.375

# FOI from Mild
gamma_Im: 0.25   # 1/4

# Severe: proportion going to H/Hbar stream (vs. nursing homes or alike)
q_ins: 0.62

# FOI from Severe, nursing homes
gamma_Is: 0.05555556  # 1/18
k_Is_noins: 0.5

# FOI from Severe, H/Hbar
alpha: 0.1    # 1/10
k_Is_ins: 0.5

# length of hospital stay
gamma_H: 0.1111111111   # 1/9
gamma_Hbar: 0.1111111111   # 1/9

# CFR
m_H: 0.22 # among hospitalized
m_Is_mult: 1.8 # RR among severe in nursing homes or alike
m_Hbar_mult: 1.5 # RR among hospital overflow

# other
k_n: 0.015 # transmission from adjacent counties

# reporting lag (days): not user-defined
H_lag: 6 
D_lag: 11

# the following effects are ADDITIVE and must sum to a number <= 1
# e.g. an effect of 0.1 reduces the intervention from 1 (full effect) to 0.9. 
# intervention effects on contact: 
school_closure_effect: 0.17
lockdown_effect: 0.67
distancing_effect: 0.3

# intervention effect on isolation/recovery for A and I_m
# this is increase in a rate of transitioning out of infectious compartment 
testing_effect_Im: 0.3
testing_effect_A: 0.2

# standard deviations, lower and upper bounds 
# of model parameters for uncertainty in projections
sd_beta_pre: 0.05
lower_beta_pre: 1.15
upper_beta_pre: 1.35

sd_q_Im: 0.01
lower_q_Im: 0.5643
upper_q_Im: 0.6043

sd_gamma_H: 0.0025
lower_gamma_H: 0.1
upper_gamma_H: 0.12

sd_m_H: 0.015
lower_m_H: 0.19
upper_m_H: 0.25

sd_m_Hbar_mult: 0.1
lower_m_Hbar_mult: 1.25
upper_m_Hbar_mult: 1.75

sd_lockdown_effect: 0.02
lower_lockdown_effect: 0.63
upper_lockdown_effect: 0.71


# not used in simulation at the moment
sd_q_A: 0.015
lower_q_A: 0.33
upper_q_A: 0.39

sd_delta: 0.025
lower_delta: 0.2
upper_delta: 0.3


### these parameters are likely not used 
# model timeframe
#timeframe: 183

# effectiveness of stay-at-home intervention: user-defined
#effect_intvx: 0.5 # NOT USED

# hospital beds occupancy: user-defined
bed_occup: 0.65 #default

# increasing hospital capacity
# capacity ramping time interval (days), not user-defined
t_C: 10 
# proportion increase (1.5 means 50 percent increase): user-defined
k_C: 1 # default

# capacity increase start date
start_C: 45 #default
start_C_min: 1
start_C_max: 180

# speed of jump
slope: 500
