
##### Epi parameters: means 
# case type distribution
q_A: 0.36 # asymptomatic
q_Im: 0.576 # mild
q_Is: 0.064 # severe

# among severe: proportion going to H/Hbar stream (vs. nursing homes or prisons)
# the value of 1 corresponds to a community transmission model
q_H: 1 #0.56

# transmissibility
beta_pre: 1.11

# latency
delta: 0.25   # 1/4

## FOI
# FOI from Asymptomatic in the absence of testing
alpha_A: 0.1428571   # 1/7 (infectious for 7 days)
k_A: 0.385 # relative infectiousness of asymptomatic compared to mildly symptomatic

# FOI from Mild
alpha_Im: 0.25   # 1/4 (infectious for 4 days, then isolated)

# FOI from Severe
alpha_Is: 0.1052632    # 1/9.5 (9.5 days between end of latency and hospitalization, 13.5 between infection and hosp)
k_Is: 0.7        # some severe cases are likely isolated sooner than 9.5 days after infection onset
                 # but probably more infectious at the beginning 

## Severe
# length of hospital stay
gamma_H: 0.11   # 1/8.8
gamma_Hbar: 0.11   

# remaining time until recovery or death, nursing homes
gamma_NH: 0.073  # 1/14 

## Mild : duration of isolation
# replace with an estimate of duration of PCR detectable virus rather than duration of infectiousness
gamma_NI: 0.1428571 # 1/7 (10 days from symptom onset - 3 days in I_m state)

## CFR
m_H: 0.21 # among hospitalized
m_NH_mult: 1.4 # RR among severe in nursing homes / prisons
m_Hbar_mult: 1.5 # RR among hospital overflow

# other
k_n: 0.015 # transmission from adjacent counties

# reporting lags (days)
H_lag: 8
D_lag: 8

# time point from candidate_state0 that becomes state0
time_num: 19

# the following effects are ADDITIVE and must sum to a number <= 1
# e.g. an effect of 0.1 reduces the intervention from 1 (full effect) to 0.9. 
# intervention effects on contact (combined in a list in the code): 
school_closure_effect: 0.165
lockdown_effect: 0.6

tot_lockdown_effect: 0.77
school_closure_prop: 0.22

# post-lockdown
ph1_release_effect: 0.07
ph2_release_effect: 0
ph3_release_effect: 0

# intervention effect on isolation/recovery for A and I_m
# this number times log(daily number of tests) is an increase in the rate of transitioning out of infectious compartment 
testing_effect: 0.04 # corresponds to compartment I_m
te_A_mult: 0.5 # relative testing effect among A compared to I_m



# standard deviations, lower and upper bounds 
# of model parameters for uncertainty in projections
sd_beta_pre: 0.05
lower_beta_pre: 1.01
upper_beta_pre: 1.21

