
##### Epi parameters: means 
beta_pre: 1.25
q_Im: 0.59
q_A: 0.36
delta: 0.25
alpha: 0.1190476
gamma_H: 0.09615385
gamma_Hbar: 0.09615385
gamma_Im: 0.25
gamma_A: 0.125
m_H: 0.36
slope: 500
k_A: 0.375
k_n: 0.05
m_Hbar_mult: 1.5

# standard deviations, lower and upper bounds 
# of model parameters for uncertainty in projections
sd_beta_pre: 0.1
lower_beta_pre: 1
upper_beta_pre: 1.5

sd_delta: 0.025
lower_delta: 0.2
upper_delta: 0.33

sd_gamma_H: 0.01
lower_gamma_H: 0.07
upper_gamma_H: 0.14

sd_m_H: 0.025
lower_m_H: 0.3
upper_m_H: 0.4

sd_m_Hbar_mult: 0.1
lower_m_Hbar_mult: 1.25
upper_m_Hbar_mult: 1.75

sd_lockdown_effect: 0.05
lower_lockdown_effect: 0.4
upper_lockdown_effect: 0.6

# model timeframe
#timeframe: 183

# reporting lag (days): not user-defined
H_lag: 6 
D_lag: 6

# effectiveness of stay-at-home intervention: user-defined
#effect_intvx: 0.5 # NOT USED

# the following effects are ADDITIVE and must sum to a number <= 1
# e.g. an effect of 0.1 reduces the intervention from 1 (full effect) to 0.9. 

# intervention effects on contact: 
school_closure_effect: 0.28
lockdown_effect: 0.48

# intervention effect on isolation/recovery for A and I_m
# this is a _reduction_ in average number of days spent in infectious state
testing_effect_Im: 1
testing_effect_A: 1

# hospital beds occupancy: user-defined
bed_occup: 0.65 #default


# increasing hospital capacity
# capacity ramping time interval (days), not user-defined
t_C: 10 
# proportion increase (1.5 means 50 percent increase): user-defined
k_C: 1 # default

# capacity increase start date
start_C: 45 #default
start_C_min: 1
start_C_max: 180
